### PR TITLE
Error Handling

### PR DESCRIPTION
**Pull request by Turntwo**
Added some additional error handling, and event to handle error in calling code.

### CODE REVIEW

**Comment by loraderon** [comment]
This looks good, thanks!

I'm going on vaccation now, and will be back in the beginning of febuary to take a better look at it and hopefully merge it.

**Comment by Turntwo** [comment]
Awesome.  As we do more testing and development with nvents, I may end up making more changes.  So let me know when you are going to merge, and I push anything we’ve done to the fork for you to evaluate and possibly include.

Love the library BTW – awesome function and simple to use.

Thanks,

Jason

**Comment by loraderon** [comment]
Sorry for dropping the ball on this.

If you have more changes, please submit them and I'll promise I'll incorporate them faster :)

**Comment by Turntwo** [comment]
No problem.  I'll have to review what I've changed, I can't remember if I pushed it all up or not.  Just got back from vacation so once I get through the backlog I'll review and let you know.

**Comment by Turntwo** [comment]
Looks like you have all the changes I've made to this point.  I'll let you know if we make any more modifications - likely as we are starting to roll a product out to customers that utilizes nvents pretty significantly.

**Pull request merged**
